In [1]:
import numpy as np
import pandas as pd
import re
import nltk

In [2]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [4]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [5]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Priyanka
[nltk_data]     Pal\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [6]:
df = pd.read_csv("spam.csv", encoding='latin-1')

In [7]:
df.shape

(5572, 5)

In [8]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [9]:
df = df[['v1', 'v2']]
df.columns = ['label', 'message']

In [10]:
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [11]:
df['label'] = df['label'].map({'ham':0, 'spam':1})
print("Label counts:")
print(df['label'].value_counts())

Label counts:
label
0    4825
1     747
Name: count, dtype: int64

In [12]:
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

In [13]:
def preprocess_text(text):
    text = text.lower()
    text = re.sub('[^a-zA-Z]', ' ', text)
    words = text.split()
    words = [ps.stem(word) for word in words if word not in stop_words]
    return " ".join(words)
df['cleaned_message'] = df['message'].apply(preprocess_text)
df[['message','cleaned_message']].head()

,message,cleaned_message
0,"Go until jurong point, crazy.. Available only ...",go jurong point crazi avail bugi n great world...
1,Ok lar... Joking wif u oni...,ok lar joke wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entri wkli comp win fa cup final tkt st m...
3,U dun say so early hor... U c already then say...,u dun say earli hor u c alreadi say
4,"Nah I don't think he goes to usf, he lives aro...",nah think goe usf live around though

In [14]:
tfidf = TfidfVectorizer(max_features=3000)
X = tfidf.fit_transform(df['cleaned_message']).toarray()
y = df['label']
X.shape

(5572, 3000)

In [15]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)
print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 4457
Testing samples: 1115

In [16]:
nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)
y_pred_nb = nb_model.predict(X_test)
nb_acc = accuracy_score(y_test, y_pred_nb)
print("Naive Bayes Accuracy:", nb_acc)

Naive Bayes Accuracy: 0.9748878923766816

In [17]:
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
y_pred_lr = lr_model.predict(X_test)
lr_acc = accuracy_score(y_test, y_pred_lr)
print("Logistic Regression Accuracy:", lr_acc)

Logistic Regression Accuracy: 0.9560538116591928

In [18]:
svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)
svm_acc = accuracy_score(y_test, y_pred_svm)
print("SVM Accuracy:", svm_acc)

SVM Accuracy: 0.979372197309417

In [19]:
print("Naive Bayes:", nb_acc)
print("Logistic Regression:", lr_acc)
print("SVM:", svm_acc)

Naive Bayes: 0.9748878923766816
Logistic Regression: 0.9560538116591928
SVM: 0.979372197309417

In [20]:
print(confusion_matrix(y_test, y_pred_lr))

[[961   4]
 [ 45 105]]

In [21]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       965
           1       0.96      0.70      0.81       150

    accuracy                           0.96      1115
   macro avg       0.96      0.85      0.89      1115
weighted avg       0.96      0.96      0.95      1115

In [22]:
def predict_sms(text):
    text = preprocess_text(text)
    vector = tfidf.transform([text]).toarray()
    prediction = lr_model.predict(vector)[0]
    if prediction == 1:
        return "Spam Message"
    else:
        return "Legitimate Message"